version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    volumes:
      - ./docker-volume/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@bla.irish
      - PGADMIN_DEFAULT_PASSWORD=admin
#    volumes:
#      - ./docker-volume/pgadmin:/var/lib/pgadmin
    ports:
      - 9000:80
    depends_on:
      - postgres